### ISSUE TITLE
Color themes for pygmentize?

### ISSUE THREAD

**Issue by amosnier** [hellerve/sbcli#25]
I feel spoiled asking this, but my what I immediately realize when starting using sbcli with pygmentize, which sounded great, is that the contrast is really too low to be usable. I have a dark pastel theme in my terminal. I have never directly used pygmentize before testing sbcli, but I have now just tried to pygmentize a Python file to standard out, and it really looks horrible. I do not really want to spend more time on this right now (I want to spend time reading my Lisp book instead) but if you have any tips on getting a different color theme with sbcli and pygmentize, I'm all ears.

Otherwise, sbcli seems really neat. Thanks for sharing it.

**Comment by hellerve** [comment]
Hey! Thanks for the feedback!

Pygments supports [styles](https://pygments.org/styles/); you can add them to the command by using `-o style=<whatever style you want>`. Now, the problem is that the options are not currently exposed by SBCLI, but I’d be happy to fix that. It will likely be a bit until I get to it, however. [The options we use are here](https://github.com/hellerve/sbcli/blob/master/repl.lisp#L298), so we could easily just pull that out into a user-accessible variable. We just haven’t done it.

Would you be willing and/or able to provide a patch? Otherwise I’d be probably able to do it in the coming week.

**Comment by amosnier** [comment]
Thanks a lot for the quick reply. Please do not consider this as urgent in any way. I am trying to pick up Lisp again because I feel it has more potential than I ever realized, and although I consider myself as an experienced programmer, when it comes to Lisp I want to spend some time with the basics. To be perfectly honest, although sbcli seems to have great potential, and I'm definitely going to keep it, I am really shopping around for the best Lisp tools at the moment, and my next step now will be to wake up my Emacs from the dead to test slime... In other words, sorry but do not count on a patch from me, at least not until further notice.

**Comment by hellerve** [comment]
No worries!

sbcli always was intended as a "quick and dirty" tool. It’s great when you want to test things out, but at some point you should probably move your experiments to a real development environment to harness the full power of the Common Lisp compiler. Seems like you are on the right track already!

**Comment by hellerve** [comment]
I’m on the train and was able to quickly hack something for both this issue and #26. SBCLI doesn’t currently work on my machine because of a readline issue, so I’m not 100% sure it works, but it should!

**Comment by amosnier** [comment]
Works perfectly, and pygmentize has zenburn, which is my favorite color scheme. Looks gorgeous, thanks a lot!

For the record:

```
~$ cat .sbclirc 
(setf *pygmentize* "/usr/bin/pygmentize")
(setf *pygmentize-options* '("-s" "-l" "lisp" "-O style=zenburn"))
```
Please note that it is an uppercase `O` for pygmentize options!
