### ISSUE TITLE
Any particular mission statement / roadmap for this project?

### ISSUE THREAD

**Issue by sudodoki** [hellerve/sbcli#5]
Hello!
Thanks for sharing this project, it's quite fun. Wondering, whether you have some specific use cases that this project covers the best or maybe, some vision/idea of what it should be?
Previously, I would be using `rlwrap sbcl` for some repl experiments. As I see now, thigs that sbcli is doing better (compared to rlwrap sbcl):

1) easier to customize prompt
2) using `cl-readline` means that it's possible to hook into completion via `(rl:register-function :complete #'complete)` and do autocomplete (which is missing from rlwrap sbcl combo, or I wasn't able to set it up)

doing worse:

1) no multiline input / paste
2) no restarts

**Comment by hellerve** [comment]
Hey!

First of all, thanks for your PRs!

Secondly, I moved away from SBCL recently, and thus do not really maintain this project anymore. If you’d like to take it over, and formulate goals/make it a fully-featured REPL, I’d be more than happy to tranfer ownership to you!

I think using `rlwrap` is alright, but I’d love it if a native REPL for SBCL existed, one that is scriptable/interactable, and possible provides better tooling support out of the box. Currently, that is not the state of the system, but I think it would be entirely possible and not too much work—at least in my naive estimate.

Cheers

**Comment by jsjolen** [comment]
Hi, I'm hi-jacking this issue a bit!

@hellerve  @sudodoki, since the library is using cl-readline (which is GPLd) then this library/application will also have to be GPLd. Just FYI :-).

**Comment by hellerve** [comment]
An update on this issue: I went back to this project today and implemented a completion function. It’s still kind of clunky, because I have to figure out how best to deal with upper- vs. lower-case defs and such.

I will probably implement both multiline input and restart as well (if I can figure out the latter).

**Comment by hellerve** [comment]
@jsjolen Is it alright if we move this discussion into a separate issue?

**Comment by hellerve** [comment]
Actually, I just added a LICENSE: MIT, which is one-way compatible with GPL v3.0, as I understand it.

**Comment by hellerve** [comment]
Another update: I added multiline input!

**Comment by hellerve** [comment]
Another update: I added restarting using `:r`. I suppose we can close this issue now, then?

**Comment by jsjolen** [comment]
It's not compatible in that way, using GPL'd code requires that your own code is licensed as GPL. I know this because this is in fact the exact same way that CLISP was GPL'd. You can read this thread and determine if I am correct or not.

https://web.archive.org/web/20140828070153/http://clisp.cvs.sourceforge.net/viewvc/clisp/clisp/doc/Why-CLISP-is-under-GPL

PS. Do what you want, I'm not here to police you I'm only trying to inform you.

**Comment by hellerve** [comment]
Oh, it’s fine, I appreciate this. I’m not a lawyer, and any help with sorting this out is great! I will grudgingly relicense this :)
